### ISSUE TITLE
Types of Gradient Button UI enhancement

### ISSUE THREAD

**Issue by Rajan232** [Rajan232/devstar-gradient-animation#7]
Instead of cycling through different types of gradients, we want to introduce a pop-up selection bar that users can select the type of gradient from. Something like the example below

![Group 1](https://github.com/Rajan232/devstar-gradient-animation/assets/63865369/0483889f-b1e5-4df5-b9de-71e627c2beec)

**Comment by RIYA1001** [comment]
I have created three different button.

<img width="960" alt="i" src="https://github.com/Rajan232/devstar-gradient-animation/assets/125476961/55c54cc7-4c4f-44aa-b057-e28df34ddbc5">
